---
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

# GitHub diff UI wraps beyond 118 characters
Layout/LineLength:
  Max: 118

# ruby style guide favorite (Homebrew style)
Style/StringLiterals:
  EnforcedStyle: double_quotes

# consistency with above
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Not used for casks and formulae.
Style/FrozenStringLiteralComment:
  Enabled: false

# Formulae and casks don't need top-level documentation
Style/Documentation:
  Enabled: false

# Allow dashes in filenames (for formula/cask names)
Naming/FileName:
  Enabled: false
