on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/kotlin-explorer.yml'
      - 'Casks/kotlin-explorer.rb'
  pull_request:
    paths:
      - '.github/workflows/kotlin-explorer.yml'
      - 'Formula/kotlin-explorer.rb'

jobs:
  install:
    runs-on: macos-latest
    env:
      HOMEBREW_COLOR: 1
      HOMEBREW_DEVELOPER: 1
    steps:
      - uses: actions/checkout@v4
      - name: brew pull & reset & tap
        run: |
          brew update-reset "$(brew --repository)"
          mkdir -p $(brew --repo)/Library/Taps/goooler
          ln -s $GITHUB_WORKSPACE $(brew --repo)/Library/Taps/goooler/homebrew-repo
      - run: brew install kotlin-explorer
      - run: brew uninstall kotlin-explorer
