name: StringResExporter

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/string-res-exporter.yml'
      - 'Formula/string-res-exporter.rb'
  pull_request:
    paths:
      - '.github/workflows/string-res-exporter.yml'
      - 'Formula/string-res-exporter.rb'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      HOMEBREW_COLOR: 1
      HOMEBREW_DEVELOPER: 1
    steps:
      - uses: actions/checkout@v4
      - name: brew pull & reset & tap
        run: |
          brew update-reset "$(brew --repository)"
          brew update-reset "$(brew --repository homebrew/cask)"
          mkdir -p $(brew --repo)/Library/Taps/goooler
          ln -s $GITHUB_WORKSPACE $(brew --repo)/Library/Taps/goooler/homebrew-repo
      - run: brew install string-res-exporter
      - run: brew uninstall string-res-exporter
